-- ========================================================
-- RATNA COACHING CENTER - SUPABASE DATABASE SCHEMA
-- ========================================================

-- 1. STUDENTS TABLE (Supports both pre-existing & new table schemas)
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT,
    email TEXT UNIQUE NOT NULL,
    mobile_number TEXT,
    target_class TEXT,
    school_name TEXT,
    roll_number TEXT,
    password_hash TEXT,
    joined_date TEXT,
    score_correct INTEGER DEFAULT 0,
    score_attempted INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ensure all required columns exist even if 'students' table was already created
ALTER TABLE public.students 
    ADD COLUMN IF NOT EXISTS student_name TEXT,
    ADD COLUMN IF NOT EXISTS mobile_number TEXT,
    ADD COLUMN IF NOT EXISTS target_class TEXT,
    ADD COLUMN IF NOT EXISTS school_name TEXT,
    ADD COLUMN IF NOT EXISTS roll_number TEXT,
    ADD COLUMN IF NOT EXISTS password_hash TEXT,
    ADD COLUMN IF NOT EXISTS joined_date TEXT,
    ADD COLUMN IF NOT EXISTS score_correct INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS score_attempted INTEGER DEFAULT 0;

-- 2. ADMISSIONS ENQUIRIES TABLE
CREATE TABLE IF NOT EXISTS public.admissions (
    id TEXT PRIMARY KEY,
    student_name TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    class_level TEXT NOT NULL,
    school_name TEXT,
    mobile_number TEXT NOT NULL,
    status TEXT DEFAULT 'Pending',
    submitted_at TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. CONTACT MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email_or_phone TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE,
    submitted_at TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. SITE DATA / ANNOUNCEMENTS TABLE
CREATE TABLE IF NOT EXISTS public.site_data (
    key TEXT PRIMARY KEY,
    content JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ========================================================
-- ROW LEVEL SECURITY (RLS) & POLICIES
-- ========================================================
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public full access to students" ON public.students;
CREATE POLICY "Public full access to students" ON public.students FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access to admissions" ON public.admissions;
CREATE POLICY "Public full access to admissions" ON public.admissions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access to contact_messages" ON public.contact_messages;
CREATE POLICY "Public full access to contact_messages" ON public.contact_messages FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access to site_data" ON public.site_data;
CREATE POLICY "Public full access to site_data" ON public.site_data FOR ALL USING (true) WITH CHECK (true);

-- ========================================================
-- REALTIME REPLICATION (SAFE DO BLOCK)
-- ========================================================
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.students;
    EXCEPTION WHEN duplicate_object THEN NULL;
              WHEN OTHERS THEN NULL;
    END;

    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.admissions;
    EXCEPTION WHEN duplicate_object THEN NULL;
              WHEN OTHERS THEN NULL;
    END;

    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.contact_messages;
    EXCEPTION WHEN duplicate_object THEN NULL;
              WHEN OTHERS THEN NULL;
    END;

    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.site_data;
    EXCEPTION WHEN duplicate_object THEN NULL;
              WHEN OTHERS THEN NULL;
    END;
END $$;
